<div class="container-fluid">
    <div>
        <h3>Payment System Settings</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Settings</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Payment System Settings</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <!--Payment System Settings (Credit system + Pro System)-->
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Payment System Settings (Credit System + Pro System)</h6>
                    <div class="payment-settings-alert"></div>
                    <form class="payment-settings" method="POST">
                        <label class="form-check-label" for="currency_symbol">Currency</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <select class="form-control show-tick" id="currency" name="currency">
                                    <option value="USD"  <?php echo ($wo['config']['currency'] == 'USD')   ? ' selected' : '';?>>USD</option>
                                    <option value="EUR" <?php echo ($wo['config']['currency'] == 'EUR')   ? ' selected' : '';?>>EUR</option>
                                    <option value="JPY" <?php echo ($wo['config']['currency'] == 'JPY')   ? ' selected' : '';?>>JPY</option>
                                    <option value="TRY" <?php echo ($wo['config']['currency'] == 'TRY')   ? ' selected' : '';?>>TRY</option>
                                    <option value="GBP" <?php echo ($wo['config']['currency'] == 'GBP')   ? ' selected' : '';?>>GBP</option>
                                    <option value="RUB" <?php echo ($wo['config']['currency'] == 'RUB')   ? ' selected' : '';?>>RUB</option>
                                    <option value="PLN" <?php echo ($wo['config']['currency'] == 'PLN')   ? ' selected' : '';?>>PLN</option>
                                    <option value="ILS" <?php echo ($wo['config']['currency'] == 'ILS')   ? ' selected' : '';?>>ILS</option>
                                    <option value="BRL" <?php echo ($wo['config']['currency'] == 'BRL')   ? ' selected' : '';?>>BRL</option>
                                    <option value="INR" <?php echo ($wo['config']['currency'] == 'INR')   ? ' selected' : '';?>>INR</option>
                                </select>
								<small class="admin-info">Set the curreny used in your site.</small>
                            </div>
                        </div>
                        <label class="form-check-label" for="currency_symbol">Currency Symbol</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="currency_symbol" name="currency_symbol" class="form-control" value="<?php echo $wo['config']['currency_symbol'];?>">
								<small class="admin-info">Choose your current symbol.</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Configure 2Checkout (Credit Cards) Payment Method  </h6>
                    <div class="checkout-settings-alert"></div>
                    <form class="checkout-settings" method="POST">
						<div>
							<div class="float-left">
								<label for="checkout_payment" class="main-label">2Checkout Payment Method</label>
								<br><small class="admin-info">Enable 2Checkout to receive payments by credit cards.</small>
							</div>
							<div class="form-group float-right switcher">
								<input type="hidden" name="checkout_payment" value="no">
								<input type="checkbox" name="checkout_payment" id="checkout_payment-enabled" value="yes" <?php echo ($wo['config']['checkout_payment'] == 'yes') ? 'checked': '';?>>
								<label for="checkout_payment-enabled" class="check-trail"><span class="check-handler"></span></label>
							</div>
							<div class="clearfix"></div>
							<hr>
						</div>
						
                        <label for="checkout_mode">2Checkout Mode</label>
						<select class="form-control show-tick" id="checkout_mode" name="checkout_mode">
                          <option value="live" <?php echo ($wo['config']['checkout_mode'] == 'live') ? 'selected': '';?>>Live</option>
                          <option value="sandbox" <?php echo ($wo['config']['checkout_mode'] == 'sandbox') ? 'selected': '';?>>SandBox</option>
                        </select>
						<small class="admin-info">Choose the mode your application is using, for testing use the SandBox mode.</small>

                        <label for="checkout_currency">2Checkout Currency</label>
                        <select class="form-control show-tick" id="checkout_currency" name="checkout_currency">
                            <option value="USD" <?php echo ($wo['config']['checkout_currency'] == 'USD')  ? ' selected': '';?>>USD</option>
                            <option value="EUR" <?php echo ($wo['config']['checkout_currency'] == 'EUR')  ? ' selected': '';?>>EUR</option>
                            <option value="AED" <?php echo ($wo['config']['checkout_currency'] == 'AED')  ? ' selected': '';?>>AED</option>
                            <option value="AFN" <?php echo ($wo['config']['checkout_currency'] == 'AFN')  ? ' selected': '';?>>AFN</option>
                            <option value="ALL" <?php echo ($wo['config']['checkout_currency'] == 'ALL')  ? ' selected': '';?>>ALL</option>
                            <option value="ARS" <?php echo ($wo['config']['checkout_currency'] == 'ARS')  ? ' selected': '';?>>ARS</option>
                            <option value="AUD" <?php echo ($wo['config']['checkout_currency'] == 'AUD')  ? ' selected': '';?>>AUD</option>
                            <option value="AZN" <?php echo ($wo['config']['checkout_currency'] == 'AZN')  ? ' selected': '';?>>AZN</option>
                            <option value="BBD" <?php echo ($wo['config']['checkout_currency'] == 'BBD')  ? ' selected': '';?>>BBD</option>
                            <option value="BDT" <?php echo ($wo['config']['checkout_currency'] == 'BDT')  ? ' selected': '';?>>BDT</option>
                            <option value="BGN" <?php echo ($wo['config']['checkout_currency'] == 'BGN')  ? ' selected': '';?>>BGN</option>
                            <option value="BMD" <?php echo ($wo['config']['checkout_currency'] == 'BMD')  ? ' selected': '';?>>BMD</option>
                            <option value="BND" <?php echo ($wo['config']['checkout_currency'] == 'BND')  ? ' selected': '';?>>BND</option>
                            <option value="BOB" <?php echo ($wo['config']['checkout_currency'] == 'BOB')  ? ' selected': '';?>>BOB</option>
                            <option value="BRL" <?php echo ($wo['config']['checkout_currency'] == 'BRL')  ? ' selected': '';?>>BRL</option>
                            <option value="BSD" <?php echo ($wo['config']['checkout_currency'] == 'BSD')  ? ' selected': '';?>>BSD</option>
                            <option value="BWP" <?php echo ($wo['config']['checkout_currency'] == 'BWP')  ? ' selected': '';?>>BWP</option>
                            <option value="BYN" <?php echo ($wo['config']['checkout_currency'] == 'BYN')  ? ' selected': '';?>>BYN</option>
                            <option value="BZD" <?php echo ($wo['config']['checkout_currency'] == 'BZD')  ? ' selected': '';?>>BZD</option>
                            <option value="CAD" <?php echo ($wo['config']['checkout_currency'] == 'CAD')  ? ' selected': '';?>>CAD</option>
                            <option value="CHF" <?php echo ($wo['config']['checkout_currency'] == 'CHF')  ? ' selected': '';?>>CHF</option>
                            <option value="CLP" <?php echo ($wo['config']['checkout_currency'] == 'CLP')  ? ' selected': '';?>>CLP</option>
                            <option value="CNY" <?php echo ($wo['config']['checkout_currency'] == 'CNY')  ? ' selected': '';?>>CNY</option>
                            <option value="COP" <?php echo ($wo['config']['checkout_currency'] == 'COP')  ? ' selected': '';?>>COP</option>
                            <option value="CRC" <?php echo ($wo['config']['checkout_currency'] == 'CRC')  ? ' selected': '';?>>CRC</option>
                            <option value="CZK" <?php echo ($wo['config']['checkout_currency'] == 'CZK')  ? ' selected': '';?>>CZK</option>
                            <option value="DKK" <?php echo ($wo['config']['checkout_currency'] == 'DKK')  ? ' selected': '';?>>DKK</option>
                            <option value="DOP" <?php echo ($wo['config']['checkout_currency'] == 'DOP')  ? ' selected': '';?>>DOP</option>
                            <option value="DZD" <?php echo ($wo['config']['checkout_currency'] == 'DZD')  ? ' selected': '';?>>DZD</option>
                            <option value="EGP" <?php echo ($wo['config']['checkout_currency'] == 'EGP')  ? ' selected': '';?>>EGP</option>
                            <option value="FJD" <?php echo ($wo['config']['checkout_currency'] == 'FJD')  ? ' selected': '';?>>FJD</option>
                            <option value="GBP" <?php echo ($wo['config']['checkout_currency'] == 'GBP')  ? ' selected': '';?>>GBP</option>
                            <option value="GTQ" <?php echo ($wo['config']['checkout_currency'] == 'GTQ')  ? ' selected': '';?>>GTQ</option>
                            <option value="HKD" <?php echo ($wo['config']['checkout_currency'] == 'HKD')  ? ' selected': '';?>>HKD</option>
                            <option value="HNL" <?php echo ($wo['config']['checkout_currency'] == 'HNL')  ? ' selected': '';?>>HNL</option>
                            <option value="HRK" <?php echo ($wo['config']['checkout_currency'] == 'HRK')  ? ' selected': '';?>>HRK</option>
                            <option value="HUF" <?php echo ($wo['config']['checkout_currency'] == 'HUF')  ? ' selected': '';?>>HUF</option>
                            <option value="IDR" <?php echo ($wo['config']['checkout_currency'] == 'IDR')  ? ' selected': '';?>>IDR</option>
                            <option value="ILS" <?php echo ($wo['config']['checkout_currency'] == 'ILS')  ? ' selected': '';?>>ILS</option>
                            <option value="INR" <?php echo ($wo['config']['checkout_currency'] == 'INR')  ? ' selected': '';?>>INR</option>
                            <option value="JMD" <?php echo ($wo['config']['checkout_currency'] == 'JMD')  ? ' selected': '';?>>JMD</option>
                            <option value="JOD" <?php echo ($wo['config']['checkout_currency'] == 'JOD')  ? ' selected': '';?>>JOD</option>
                            <option value="JPY" <?php echo ($wo['config']['checkout_currency'] == 'JPY')  ? ' selected': '';?>>JPY</option>
                            <option value="KES" <?php echo ($wo['config']['checkout_currency'] == 'KES')  ? ' selected': '';?>>KES</option>
                            <option value="KRW" <?php echo ($wo['config']['checkout_currency'] == 'KRW')  ? ' selected': '';?>>KRW</option>
                            <option value="KWD" <?php echo ($wo['config']['checkout_currency'] == 'KWD')  ? ' selected': '';?>>KWD</option>
                            <option value="KZT" <?php echo ($wo['config']['checkout_currency'] == 'KZT')  ? ' selected': '';?>>KZT</option>
                            <option value="LAK" <?php echo ($wo['config']['checkout_currency'] == 'LAK')  ? ' selected': '';?>>LAK</option>
                            <option value="LBP" <?php echo ($wo['config']['checkout_currency'] == 'LBP')  ? ' selected': '';?>>LBP</option>
                            <option value="LKR" <?php echo ($wo['config']['checkout_currency'] == 'LKR')  ? ' selected': '';?>>LKR</option>
                            <option value="LRD" <?php echo ($wo['config']['checkout_currency'] == 'LRD')  ? ' selected': '';?>>LRD</option>
                            <option value="MAD" <?php echo ($wo['config']['checkout_currency'] == 'MAD')  ? ' selected': '';?>>MAD</option>
                            <option value="MDL" <?php echo ($wo['config']['checkout_currency'] == 'MDL')  ? ' selected': '';?>>MDL</option>
                            <option value="MMK" <?php echo ($wo['config']['checkout_currency'] == 'MMK')  ? ' selected': '';?>>MMK</option>
                            <option value="MOP" <?php echo ($wo['config']['checkout_currency'] == 'MOP')  ? ' selected': '';?>>MOP</option>
                            <option value="MRO" <?php echo ($wo['config']['checkout_currency'] == 'MRO')  ? ' selected': '';?>>MRO</option>
                            <option value="MUR" <?php echo ($wo['config']['checkout_currency'] == 'MUR')  ? ' selected': '';?>>MUR</option>
                            <option value="MVR" <?php echo ($wo['config']['checkout_currency'] == 'MVR')  ? ' selected': '';?>>MVR</option>
                            <option value="MXN" <?php echo ($wo['config']['checkout_currency'] == 'MXN')  ? ' selected': '';?>>MXN</option>
                            <option value="MYR" <?php echo ($wo['config']['checkout_currency'] == 'MYR')  ? ' selected': '';?>>MYR</option>
                            <option value="NAD" <?php echo ($wo['config']['checkout_currency'] == 'NAD')  ? ' selected': '';?>>NAD</option>
                            <option value="NGN" <?php echo ($wo['config']['checkout_currency'] == 'NGN')  ? ' selected': '';?>>NGN</option>
                            <option value="NIO" <?php echo ($wo['config']['checkout_currency'] == 'NIO')  ? ' selected': '';?>>NIO</option>
                            <option value="NOK" <?php echo ($wo['config']['checkout_currency'] == 'NOK')  ? ' selected': '';?>>NOK</option>
                            <option value="NPR" <?php echo ($wo['config']['checkout_currency'] == 'NPR')  ? ' selected': '';?>>NPR</option>
                            <option value="NZD" <?php echo ($wo['config']['checkout_currency'] == 'NZD')  ? ' selected': '';?>>NZD</option>
                            <option value="OMR" <?php echo ($wo['config']['checkout_currency'] == 'OMR')  ? ' selected': '';?>>OMR</option>
                            <option value="PEN" <?php echo ($wo['config']['checkout_currency'] == 'PEN')  ? ' selected': '';?>>PEN</option>
                            <option value="PGK" <?php echo ($wo['config']['checkout_currency'] == 'PGK')  ? ' selected': '';?>>PGK</option>
                            <option value="PHP" <?php echo ($wo['config']['checkout_currency'] == 'PHP')  ? ' selected': '';?>>PHP</option>
                            <option value="PKR" <?php echo ($wo['config']['checkout_currency'] == 'PKR')  ? ' selected': '';?>>PKR</option>
                            <option value="PLN" <?php echo ($wo['config']['checkout_currency'] == 'PLN')  ? ' selected': '';?>>PLN</option>
                            <option value="PYG" <?php echo ($wo['config']['checkout_currency'] == 'PYG')  ? ' selected': '';?>>PYG</option>
                            <option value="QAR" <?php echo ($wo['config']['checkout_currency'] == 'QAR')  ? ' selected': '';?>>QAR</option>
                            <option value="RON" <?php echo ($wo['config']['checkout_currency'] == 'RON')  ? ' selected': '';?>>RON</option>
                            <option value="RSD" <?php echo ($wo['config']['checkout_currency'] == 'RSD')  ? ' selected': '';?>>RSD</option>
                            <option value="RUB" <?php echo ($wo['config']['checkout_currency'] == 'RUB')  ? ' selected': '';?>>RUB</option>
                            <option value="SAR" <?php echo ($wo['config']['checkout_currency'] == 'SAR')  ? ' selected': '';?>>SAR</option>
                            <option value="SBD" <?php echo ($wo['config']['checkout_currency'] == 'SBD')  ? ' selected': '';?>>SBD</option>
                            <option value="SCR" <?php echo ($wo['config']['checkout_currency'] == 'SCR')  ? ' selected': '';?>>SCR</option>
                            <option value="SEK" <?php echo ($wo['config']['checkout_currency'] == 'SEK')  ? ' selected': '';?>>SEK</option>
                            <option value="SGD" <?php echo ($wo['config']['checkout_currency'] == 'SGD')  ? ' selected': '';?>>SGD</option>
                            <option value="SYP" <?php echo ($wo['config']['checkout_currency'] == 'SYP')  ? ' selected': '';?>>SYP</option>
                            <option value="THB" <?php echo ($wo['config']['checkout_currency'] == 'THB')  ? ' selected': '';?>>THB</option>
                            <option value="TND" <?php echo ($wo['config']['checkout_currency'] == 'TND')  ? ' selected': '';?>>TND</option>
                            <option value="TOP" <?php echo ($wo['config']['checkout_currency'] == 'TOP')  ? ' selected': '';?>>TOP</option>
                            <option value="TRY" <?php echo ($wo['config']['checkout_currency'] == 'TRY')  ? ' selected': '';?>>TRY</option>
                            <option value="TTD" <?php echo ($wo['config']['checkout_currency'] == 'TTD')  ? ' selected': '';?>>TTD</option>
                            <option value="TWD" <?php echo ($wo['config']['checkout_currency'] == 'TWD')  ? ' selected': '';?>>TWD</option>
                            <option value="UAH" <?php echo ($wo['config']['checkout_currency'] == 'UAH')  ? ' selected': '';?>>UAH</option>
                            <option value="UYU" <?php echo ($wo['config']['checkout_currency'] == 'UYU')  ? ' selected': '';?>>UYU</option>
                            <option value="VND" <?php echo ($wo['config']['checkout_currency'] == 'VND')  ? ' selected': '';?>>VND</option>
                            <option value="VUV" <?php echo ($wo['config']['checkout_currency'] == 'VUV')  ? ' selected': '';?>>VUV</option>
                            <option value="WST" <?php echo ($wo['config']['checkout_currency'] == 'WST')  ? ' selected': '';?>>WST</option>
                            <option value="XCD" <?php echo ($wo['config']['checkout_currency'] == 'XCD')  ? ' selected': '';?>>XCD</option>
                            <option value="XOF" <?php echo ($wo['config']['checkout_currency'] == 'XOF')  ? ' selected': '';?>>XOF</option>
                            <option value="YER" <?php echo ($wo['config']['checkout_currency'] == 'YER')  ? ' selected': '';?>>YER</option>
                            <option value="ZAR" <?php echo ($wo['config']['checkout_currency'] == 'ZAR')  ? ' selected': '';?>>ZAR</option>
                        </select>
						<small class="admin-info">Set your 2checkout currency, this will be used only on 2checkout.</small>
                        <div class="clearfix"></div>

                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Seller ID</label>
                                <input type="text" id="checkout_seller_id" name="checkout_seller_id" class="form-control" value="<?php echo $wo['config']['checkout_seller_id'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Publishable Key</label>
                                <input type="text" id="checkout_publishable_key" name="checkout_publishable_key" class="form-control" value="<?php echo $wo['config']['checkout_publishable_key'];?>">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Private Key</label>
                                <input type="text" id="checkout_private_key" name="checkout_private_key" class="form-control" value="<?php echo $wo['config']['checkout_private_key'];?>">
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Configure CashFree (Credit Cards) Payment Method</h6>
                    <div class="cashfree-settings-alert"></div>
                    <form class="cashfree-settings" method="POST">
						<div>
							<div class="float-left">
								<label for="cashfree_payment" class="main-label">Cashfree Payment Method</label>
								<br><small class="admin-info">Enable CashFree to receive payments by credit cards.</small>
							</div>
							<div class="form-group float-right switcher">
								<input type="hidden" name="cashfree_payment" value="no">
								<input type="checkbox" name="cashfree_payment" id="cashfree_payment-enabled" value="yes" <?php echo ($wo['config']['cashfree_payment'] == 'yes') ? 'checked': '';?>>
								<label for="cashfree_payment-enabled" class="check-trail"><span class="check-handler"></span></label>
							</div>
							<div class="clearfix"></div>
							<hr>
						</div>
						
						<label for="cashfree_mode">Cashfree Mode</label>
						<select class="form-control show-tick" id="cashfree_mode" name="cashfree_mode">
                          <option value="live" <?php echo ($wo['config']['cashfree_mode'] == 'live') ? 'selected': '';?>>Live</option>
                          <option value="sandbox" <?php echo ($wo['config']['cashfree_mode'] == 'sandbox') ? 'selected': '';?>>SandBox</option>
                        </select>
						<small class="admin-info">Choose the mode your application is using, for testing use the SandBox mode.</small>
						
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Client Id</label>
                                <input type="text" id="cashfree_client_key" name="cashfree_client_key" class="form-control" value="<?php echo $wo['config']['cashfree_client_key'];?>">
								<small class="admin-info">Your application client ID.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Client Secret</label>
                                <input type="text" id="cashfree_secret_key" name="cashfree_secret_key" class="form-control" value="<?php echo $wo['config']['cashfree_secret_key'];?>">
								<small class="admin-info">Your application client ID secret key.</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Configure PayStack (Credit Cards) Payment Method</h6>
                    <div class="paystack-settings-alert"></div>
                    <form class="paystack-settings" method="POST">
						<div>
							<div class="float-left">
								<label for="paystack_payment" class="main-label">PayStack Payment Method</label>
								<br><small class="admin-info">Get paid by Paystack payment provider.</small>
							</div>
							<div class="form-group float-right switcher">
								<input type="hidden" name="paystack_payment" value="no">
								<input type="checkbox" name="paystack_payment" id="paystack_payment-enabled" value="yes" <?php echo ($wo['config']['paystack_payment'] == 'yes') ? 'checked': '';?>>
								<label for="paystack_payment-enabled" class="check-trail"><span class="check-handler"></span></label>
							</div>
							<div class="clearfix"></div>
							<hr>
						</div>
						
                        <div class="clearfix"></div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Secret Key</label>
                                <input type="text" id="paystack_secret_key" name="paystack_secret_key" class="form-control" value="<?php echo $wo['config']['paystack_secret_key'];?>">
								<small class="admin-info">Your paystack account secret key.</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Configure Local Bank Payment Method </h6>
                    <div class="bank-settings-alert"></div>
                    <form class="bank-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Bank Description</label>
                                <textarea name="bank_description" id="bank_description" class="form-control" cols="30" rows="5"><?php echo $wo['config']['bank_description']; ?></textarea>
								<small class="admin-info">Set your IBAN, SWIFT code from the code above.</small>
                            </div>
                        </div>
						<hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Bank transfer note</label>
                                <textarea name="bank_transfer_note" id="bank_transfer_note" class="form-control" cols="30" rows="5"><?php echo $wo['config']['bank_transfer_note']; ?></textarea>
								<small class="admin-info">Your note to the custoemr after he submits the payment.</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Configure PaySera Payment Method</h6>
                    <div class="pay-settings-alert"></div>
                    <form class="pay-settings" method="POST">
						<label for="paysera_test_mode">PaySera Mode</label>
						<select class="form-control show-tick" id="paysera_test_mode" name="paysera_test_mode">
                          <option value="live" <?php echo ($wo['config']['paysera_test_mode'] == 'live') ? 'selected': '';?>>Live</option>
                          <option value="test" <?php echo ($wo['config']['paysera_test_mode'] == 'test') ? 'selected': '';?>>Test</option>
                        </select>
						<small class="admin-info">Choose the mode your application is using, for testing use the SandBox mode.</small>
						<div class="clearfix"></div>
                        <label for="currency_symbol">Project ID</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="paysera_project_id" name="paysera_project_id" class="form-control" value="<?php echo $wo['config']['paysera_project_id'];?>">
								<small class="admin-info">Your PaySera project ID.</small>
                            </div>
                        </div>
                        <label class="form-check-label" for="currency_symbol">Project password</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="paysera_password" name="paysera_password" class="form-control" value="<?php echo $wo['config']['paysera_password'];?>">
								<small class="admin-info">Your PaySera account password.</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Authorize.Net Payment Settings</h6>
                    <div class="authorize-settings-alert"></div>
                    <form class="authorize-settings" method="POST">
						<div>
							<div class="float-left">
								<label for="authorize_payment" class="main-label">Authorize.Net Payment Method</label>
								<br><small class="admin-info">Enable Authorize.Net to receive payments by credit cards.</small>
							</div>
							<div class="form-group float-right switcher">
								<input type="hidden" name="authorize_payment" value="no">
								<input type="checkbox" name="authorize_payment" id="authorize_payment-enabled" value="yes" <?php echo ($wo['config']['authorize_payment'] == 'yes') ? 'checked': '';?>>
								<label for="authorize_payment-enabled" class="check-trail"><span class="check-handler"></span></label>
							</div>
							<div class="clearfix"></div>
							<label for="authorize_test_mode">Test mode</label>
						<select class="form-control show-tick" id="authorize_test_mode" name="authorize_test_mode">
                          <option value="PRODUCTION" <?php echo ($wo['config']['authorize_test_mode'] == 'PRODUCTION') ? 'selected': '';?>>Live</option>
                          <option value="SANDBOX" <?php echo ($wo['config']['authorize_test_mode'] == 'SANDBOX') ? 'selected': '';?>>Test</option>
                        </select>
						<small class="admin-info">Choose the mode your application is using, for testing use the SandBox mode.</small>
						<div class="clearfix"></div>
							<hr>
						</div>
						
                        <label for="authorize_login_id">Authorize.Net API LOGIN ID</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="authorize_login_id" name="authorize_login_id" class="form-control" value="<?php echo $wo['config']['authorize_login_id'];?>">
								<small class="admin-info">Your Authorize.Net API LOGIN ID.</small>
                            </div>
                        </div>
                        <label class="form-check-label" for="authorize_transaction_key">Authorize.Net TRANSACTION KEY</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="authorize_transaction_key" name="authorize_transaction_key" class="form-control" value="<?php echo $wo['config']['authorize_transaction_key'];?>">
								<small class="admin-info">Your Authorize.Net TRANSACTION KEY.</small>
                            </div>
                        </div>
                        
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
        </div>

        <!--Paypal payment-->
        <div class="col-lg-6 col-md-6 float-right">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">PayPal Payment Settings</h6>
                    <div class="paypal-settings-alert"></div>
                    <form class="paypal-settings" method="POST">
                        <label for="paypal_mode">PayPal Mode</label>
						<select class="form-control show-tick" id="paypal_mode" name="paypal_mode">
                          <option value="live" <?php echo ($wo['config']['paypal_mode'] == 'live') ? 'selected': '';?>>Live</option>
                          <option value="sandbox" <?php echo ($wo['config']['paypal_mode'] == 'sandbox') ? 'selected': '';?>>SandBox</option>
                        </select>
						<small class="admin-info">Choose the mode your application is using, for testing use the SandBox mode.</small>
						<div class="clearfix"></div>

                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">PayPal Client ID</label>
                                <input type="text" id="paypal_id" name="paypal_id" class="form-control" value="<?php echo $wo['config']['paypal_id'];?>">
								<small class="admin-info">Set your PayPal application ID.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">PayPal Secret Key</label>
                                <input type="text" id="paypal_secret" name="paypal_secret" class="form-control" value="<?php echo $wo['config']['paypal_secret'];?>">
								<small class="admin-info">Set your PayPal application secret key.</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Configure Stripe (Credit Cards) Payment Method</h6>
                    <div class="stripe-settings-alert"></div>
                    <form class="stripe-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Stripe version</label>
                                <input type="text" id="stripe_version" name="stripe_version" class="form-control" value="<?php echo $wo['config']['stripe_version'];?>">
								<small class="admin-info">Set Stripe API version.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Stripe API Secret Key</label>
                                <input type="text" id="stripe_secret" name="stripe_secret" class="form-control" value="<?php echo $wo['config']['stripe_secret'];?>">
								<small class="admin-info">Your Stripe secret key that starts with sk_</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Stripe Publishable Key</label>
                                <input type="text" id="stripe_id" name="stripe_id" class="form-control" value="<?php echo $wo['config']['stripe_id'];?>">
								<small class="admin-info">Your Stripe publishable key that starts with pk_</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Iyzipay Payment Settings</h6>
                    <div class="iyzipay-settings-alert"></div>
                    <form class="iyzipay-settings" method="POST">
						<div>
							<div class="float-left">
								<label for="iyzipay_payment" class="main-label">Iyzipay Payment Method</label>
								<br><small class="admin-info">Enable Iyzipay to receive payments by credit cards.</small>
							</div>
							<div class="form-group float-right switcher">
								<input type="hidden" name="iyzipay_payment" value="no">
								<input type="checkbox" name="iyzipay_payment" id="iyzipay_payment-enabled" value="yes" <?php echo ($wo['config']['iyzipay_payment'] == 'yes') ? 'checked': '';?>>
								<label for="iyzipay_payment-enabled" class="check-trail"><span class="check-handler"></span></label>
							</div>
							<div class="clearfix"></div>
							<hr>
						</div>
						
                        <label for="iyzipay_mode">Iyzipay Mode</label>
						<select class="form-control show-tick" id="iyzipay_mode" name="iyzipay_mode">
                          <option value="0" <?php echo ($wo['config']['iyzipay_mode'] == '0') ? 'selected': '';?>>Live</option>
                          <option value="1" <?php echo ($wo['config']['iyzipay_mode'] == '1') ? 'selected': '';?>>SandBox</option>
                        </select>
						<small class="admin-info">Choose the mode your application is using, for testing use the SandBox mode.</small>
						<div class="clearfix"></div>

                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Key</label>
                                <input type="text" id="iyzipay_key" name="iyzipay_key" class="form-control" value="<?php echo $wo['config']['iyzipay_key'];?>">
								
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Secret Key</label>
                                <input type="text" id="iyzipay_secret_key" name="iyzipay_secret_key" class="form-control" value="<?php echo $wo['config']['iyzipay_secret_key'];?>">
								
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Id</label>
                                <input type="text" id="iyzipay_buyer_id" name="iyzipay_buyer_id" class="form-control" value="<?php echo $wo['config']['iyzipay_buyer_id'];?>">
								
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Name</label>
                                <input type="text" id="iyzipay_buyer_name" name="iyzipay_buyer_name" class="form-control" value="<?php echo $wo['config']['iyzipay_buyer_name'];?>">
								
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Surname</label>
                                <input type="text" id="iyzipay_buyer_surname" name="iyzipay_buyer_surname" class="form-control" value="<?php echo $wo['config']['iyzipay_buyer_surname'];?>">
								
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Gsm Number (+905350000000)</label>
                                <input type="text" id="iyzipay_buyer_gsm_number" name="iyzipay_buyer_gsm_number" class="form-control" value="<?php echo $wo['config']['iyzipay_buyer_gsm_number'];?>">
								
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Email</label>
                                <input type="text" id="iyzipay_buyer_email" name="iyzipay_buyer_email" class="form-control" value="<?php echo $wo['config']['iyzipay_buyer_email'];?>">
								
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Identity Number</label>
                                <input type="text" id="iyzipay_identity_number" name="iyzipay_identity_number" class="form-control" value="<?php echo $wo['config']['iyzipay_identity_number'];?>">
								
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Address</label>
                                <input type="text" id="iyzipay_address" name="iyzipay_address" class="form-control" value="<?php echo $wo['config']['iyzipay_address'];?>">
								
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer City</label>
                                <input type="text" id="iyzipay_city" name="iyzipay_city" class="form-control" value="<?php echo $wo['config']['iyzipay_city'];?>">
								
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Country</label>
                                <input type="text" id="iyzipay_country" name="iyzipay_country" class="form-control" value="<?php echo $wo['config']['iyzipay_country'];?>">
								
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Iyzipay Buyer Zip</label>
                                <input type="text" id="iyzipay_zip" name="iyzipay_zip" class="form-control" value="<?php echo $wo['config']['iyzipay_zip'];?>">
								
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                  <h6 class="card-title">PayU Payment Settings</h6>
                    <div class="payu-settings-alert"></div>
                    <form class="payu-settings" method="POST">
						<div>
							<div class="float-left">
								<label for="payu_payment" class="main-label">PayU Payment Method</label>
								<br><small class="admin-info">Enable PayU to receive payments by credit cards.</small>
							</div>
							<div class="form-group float-right switcher">
								<input type="hidden" name="payu_payment" value="no">
								<input type="checkbox" name="payu_payment" id="payu_payment-enabled" value="yes" <?php echo ($wo['config']['payu_payment'] == 'yes') ? 'checked': '';?>>
								<label for="payu_payment-enabled" class="check-trail"><span class="check-handler"></span></label>
							</div>
							<div class="clearfix"></div>
							<hr>
						</div>
						
						<label for="payu_mode">PayU Mode</label>
						<select class="form-control show-tick" id="payu_mode" name="payu_mode">
                          <option value="0" <?php echo ($wo['config']['payu_mode'] == '0') ? 'selected': '';?>>Live</option>
                          <option value="1" <?php echo ($wo['config']['payu_mode'] == '1') ? 'selected': '';?>>SandBox</option>
                        </select>
						<small class="admin-info">Choose the mode your application is using, for testing use the SandBox mode.</small>
						<div class="clearfix"></div>

                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">Merchant Id</label>
                                <input type="text" id="payu_merchant_id" name="payu_merchant_id" class="form-control" value="<?php echo $wo['config']['payu_merchant_id'];?>">
                                
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">Secret Key</label>
                                <input type="text" id="payu_secret_key" name="payu_secret_key" class="form-control" value="<?php echo $wo['config']['payu_secret_key'];?>">
                                
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">PayU Buyer Name</label>
                                <input type="text" id="payu_buyer_name" name="payu_buyer_name" class="form-control" value="<?php echo $wo['config']['payu_buyer_name'];?>">
                                
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">PayU Buyer Surname</label>
                                <input type="text" id="payu_buyer_surname" name="payu_buyer_surname" class="form-control" value="<?php echo $wo['config']['payu_buyer_surname'];?>">
                                
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">PayU Buyer Gsm Number (+905350000000)</label>
                                <input type="text" id="payu_buyer_gsm_number" name="payu_buyer_gsm_number" class="form-control" value="<?php echo $wo['config']['payu_buyer_gsm_number'];?>">
                                
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                              <label class="form-label">PayU Buyer Email</label>
                                <input type="text" id="payu_buyer_email" name="payu_buyer_email" class="form-control" value="<?php echo $wo['config']['payu_buyer_email'];?>">
                                
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Securionpay Payment Settings</h6>
                    <div class="securionpay-settings-alert"></div>
                    <form class="securionpay-settings" method="POST">
						<div>
							<div class="float-left">
								<label for="securionpay_payment" class="main-label">Securionpay Payment Method</label>
								<br><small class="admin-info">Enable Securionpay to receive payments by credit cards.</small>
							</div>
							<div class="form-group float-right switcher">
								<input type="hidden" name="securionpay_payment" value="no">
								<input type="checkbox" name="securionpay_payment" id="securionpay_payment-enabled" value="yes" <?php echo ($wo['config']['securionpay_payment'] == 'yes') ? 'checked': '';?>>
								<label for="securionpay_payment-enabled" class="check-trail"><span class="check-handler"></span></label>
							</div>
							<div class="clearfix"></div>
							<hr>
						</div>
						
                        <label for="securionpay_public_key">Securionpay Public key</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="securionpay_public_key" name="securionpay_public_key" class="form-control" value="<?php echo $wo['config']['securionpay_public_key'];?>">
								
                            </div>
                        </div>
                        <label class="form-check-label" for="securionpay_secret_key">Securionpay Secret key</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="securionpay_secret_key" name="securionpay_secret_key" class="form-control" value="<?php echo $wo['config']['securionpay_secret_key'];?>">
								
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function() {
    $('.switcher input[type=checkbox]').click(function () {
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        if ($(this).is(":checked") === true) {
            objData[configName] = $(this).val();
        }
        else{
            if ($('input[name='+configName+']')[0]) {
                objData[configName] = $($('input[name='+configName+']')[0]).val();
            }
        }
        objData['hash_id'] = hash_id;
        $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
    $('input[type=text], input[type=number], input[type=password], textarea').on('keyup', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));
});
</script>